[general]
import = ["~/.config/alacritty/safe.toml"]

[window]
decorations_theme_variant = "Dark"
resize_increments = true
dimensions = { columns = 120, lines = 35 }
position = { x = 200, y = 200 }
title = ""

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
# Original Perfect DOS VGA by Zeh Fernando and  narrower, "less perfect", by
# Adam Moore
# - https://zehfernando.com/2015/revisiting-vga-fonts/
# - https://laemeur.sdf.org/fonts/
normal = { family = "Less Perfect DOS VGA" } 
size = 20.0
