[general]
import = ["~/.config/alacritty/safe.toml"]

[window]
decorations_theme_variant = "Dark"
resize_increments = true
dimensions = { columns = 120, lines = 35 }
position = { x = 200, y = 200 }
title = ""

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
# normal      = { family = "Iosevka", style = "Light" }
# italic      = { family = "Iosevka", style = "Light Italic" }
# bold        = { family = "Iosevka", style = "Medium" }
# bold_italic = { family = "Iosevka", style = "Bold Italic" }
#normal = { family = "AcPlus IBM VGA 9x16" }
normal = { family = "Perfect DOS VGA 437" }
# normal = { family = "GitLab Mono", style = "Light" }
# normal = { family = "Monaco", style = "Regular" }
size = 20.0
