[general]
import = ["~/Code/OSS/alacritty-theme/themes/hardhacker.toml"]

[window]
decorations_theme_variant = "Dark"
resize_increments = true
dimensions = { columns = 120, lines = 35 }
position = { x = 200, y = 200 }
title = ""

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
normal = { family = "GitLab Mono", style = "Medium" } 
bold = { family = "GitLab Mono", style = "ExtraBold" } 
# normal = { family = "Less Perfect DOS VGA" } 
# normal = { family = "AcPlus IBM VGA 9x16" }
size = 20.0
