[window]
decorations_theme_variant = "Dark"
resize_increments = true
dimensions = { columns = 120, lines = 35 }
position = { x = 200, y = 200 }
title = ""

[cursor]
style = { shape = "Block", blinking = "Always" }

[font]
normal      = { family = "Iosevka", style = "Light" }
italic      = { family = "Iosevka", style = "Light Italic" }
bold        = { family = "Iosevka", style = "Medium" }
bold_italic = { family = "Iosevka", style = "Bold Italic" }
size = 18.0

[colors.cursor]
text   = "#000000"
cursor = "#ffd800"

[colors.primary]
foreground = "#dadada"
background = "#111111"

[colors.normal]
black   = "#111111"
red     = "#fd5e00"
green   = "#00875f"
yellow  = "#ffd800"
blue    = "#00508F"
magenta = "#870087"
cyan    = "#00605f"
white   = "#9e9e9e"

[colors.bright]
black   = "#3a3a3a"
red     = "#ff875f"
green   = "#01af87"
yellow  = "#ffff5f"
blue    = "#01afff"
magenta = "#875faf"
cyan    = "#008787"
white   = "#dadada"
