[colors.cursor]
text = "#000000"
cursor = "#FF00FF"

[colors.primary]
foreground = "#dddddd"
background = "#000000"

[colors.normal]
black = "#000000"
red = "#bb0000"
green = "#00bb00"
yellow = "#bbbb00"
blue = "#0000bb"
magenta = "#bb00bb"
cyan = "#00bbbb"
white = "#bbbbbb"

[colors.bright]
black = "#333333"
red = "#ff0000"
green = "#00ff00"
yellow = "#ffff00"
blue = "#0000ff"
magenta = "#ff00ff"
cyan = "#00ffff"
white = "#ffffff"

