[colors.cursor]
text   = "#000000"
cursor = "#ff00ff"

[colors.primary]
foreground = "#DDD1B5"
background = "#000000"

[colors.normal]
black   = "#17140D"
red     = "#fd5e00"
green   = "#00875f"
yellow  = "#ffd800"
blue    = "#00508F"
magenta = "#870087"
cyan    = "#00605f"
white   = "#baa87f"

[colors.bright]
black   = "#382d14"
red     = "#ff875f"
green   = "#01af87"
yellow  = "#ffff5f"
blue    = "#01afff"
magenta = "#875faf"
cyan    = "#008787"
white   = "#DDD1B5"
