[window]
decorations_theme_variant = "Dark"
resize_increments = true
dimensions = { columns = 120, lines = 35 }
position = { x = 200, y = 200 }
title = ""

[cursor]
style = { shape = "Block", blinking = "Always" }

[colors.cursor]
text = '#000000'
cursor = '#ff00ff'

[font]
normal = { family = "GitLab Mono", style = "Regular" } 
bold = { family = "GitLab Mono", style = "Bold" } 
size = 18.0
offset = { x = 0, y = 4 }
glyph_offset = { x = 0, y = 2 }
