[window]
decorations_theme_variant = "Dark"

[font]
normal = { family = "Terminus (TTF)" }
size = 16

# # XTerm's default colors
#
# # Default colors
# [colors.primary]
# background = '#000000'
# foreground = '#ffffff'
#
# # Normal colors
# [colors.normal]
# black   = '#000000'
# red     = '#cd0000'
# green   = '#00cd00'
# yellow  = '#cdcd00'
# blue    = '#0000ee'
# magenta = '#cd00cd'
# cyan    = '#00cdcd'
# white   = '#e5e5e5'
#
# # Bright colors
# [colors.bright]
# black   = '#7f7f7f'
# red     = '#ff0000'
# green   = '#00ff00'
# yellow  = '#ffff00'
# blue    = '#5c5cff'
# magenta = '#ff00ff'
# cyan    = '#00ffff'
# white   = '#ffffff'

# Amber CRT Terminal Color Palette for Alacritty
# Replicates the warm amber phosphor look of classic terminals

# [colors.primary]
# background = "#000000"  # Pure black background
# foreground = "#ffaa00"  # Primary amber text color
#
# [colors.cursor]
# text = "#000000"
# cursor = "#ffaa00"
#
# [colors.selection]
# text = "#000000"
# background = "#cc8800"
#
# # Normal colors - all variations within the amber spectrum
# [colors.normal]
# black   = "#000000"  # True black
# red     = "#cc4400"  # Deep amber-red (dim)
# green   = "#bb8800"  # Amber-yellow (medium)
# yellow  = "#ddaa00"  # Bright amber-yellow
# blue    = "#996600"  # Muted amber-brown (darkest)
# magenta = "#dd8800"  # Amber-orange
# cyan    = "#ccaa44"  # Light amber
# white   = "#ffaa00"  # Primary amber
#
# # Bright colors - shifted toward yellow-white for "glow" effect
# [colors.bright]
# black   = "#333300"  # Dark amber-brown
# red     = "#ff6600"  # Bright amber-red
# green   = "#ffcc00"  # Golden amber
# yellow  = "#ffdd44"  # Bright golden yellow
# blue    = "#cc8800"  # Medium amber
# magenta = "#ffaa44"  # Bright amber-orange
# cyan    = "#ffdd88"  # Very light amber
# white   = "#ffffaa"  # Near-white with amber tint
#
# [colors.dim]
# black   = "#000000"
# red     = "#884400"
# green   = "#996600"
# yellow  = "#aa7700"
# blue    = "#664400"
# magenta = "#aa5500"
# cyan    = "#aa8833"
# white   = "#cc8800"

# Orange Amber CRT Terminal Color Palette for Alacritty
# Replicates the warm orange-amber phosphor look of classic terminals

[colors.primary]
background = "#000000"  # Pure black background
foreground = "#ff9900"  # Primary orange-amber text color

[colors.cursor]
text = "#000000"
cursor = "#ff9900"

[colors.selection]
text = "#000000"
background = "#cc6600"

# Normal colors - all variations within the orange-amber spectrum
[colors.normal]
black   = "#000000"  # True black
red     = "#cc3300"  # Deep orange-red (dim)
green   = "#cc7700"  # Orange-amber (medium)
yellow  = "#dd8800"  # Bright orange-amber
blue    = "#aa6600"  # Muted orange-brown
magenta = "#dd6600"  # Pure orange-amber
cyan    = "#cc8844"  # Light orange-amber
white   = "#ff9900"  # Primary orange-amber

# Bright colors - shifted toward yellow for "glow" effect
[colors.bright]
black   = "#442200"  # Dark orange-brown
red     = "#ff5500"  # Bright orange-red
green   = "#ffaa00"  # Golden orange
yellow  = "#ffbb00"  # Bright golden orange
blue    = "#cc7700"  # Medium orange
magenta = "#ff8800"  # Bright orange
cyan    = "#ffaa66"  # Very light orange
white   = "#ffcc88"  # Near-white with orange tint

# Optional: Dim colors for even more authentic CRT feel
# Uncomment if your terminal supports them
[colors.dim]
black   = "#000000"
red     = "#772200"
green   = "#885500"
yellow  = "#996600"
blue    = "#775500"
magenta = "#884400"
cyan    = "#997733"
white   = "#bb6600"
