#!/usr/bin/env bash

yabai -m config layout bsp
yabai -m config window_gap 0
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0

# yabai -m focus_follows_mouse autofocus

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="Microsoft Teams$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
