# make windows and pane numbers start at 1 instead of 0
set -g base-index 1 
set-window-option -g pane-base-index 1

# automatically renumber windows
set -g renumber-windows on

# unbind C-b and set it to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# use vi keybindings
setw -g mode-keys vi

# make delay shorter
set -sg escape-time 0

# split panes with | and - and unbind default split keys
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# pane movement like vim
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane movement like vim
bind H resize-pane -L 10
bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -R 10

# bind r to refresh config
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"


# Thank you Ham Vocke and Nick Nisi
# - http://www.hamvocke.com/blog/a-quick-and-easy-guide-to-tmux/
# - http://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# - https://github.com/nicknisi/dotfiles/blob/master/tmux/tmux.conf.symlink

